# Generated by Django 2.2.3 on 2019-09-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0002_auto_20190727_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.BooleanField(default=False)),
                ('webrtc_flag', models.BooleanField(default=False)),
                ('admin_flag', models.BooleanField(default=False)),
                ('account', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=16)),
                ('login_count', models.IntegerField(default=1)),
                ('latest_login', models.DateTimeField()),
                ('created_datetime', models.DateTimeField()),
                ('modified_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
