# Generated by Django 2.2.3 on 2019-09-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uid',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
