# Generated by Django 2.2.3 on 2019-09-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0004_auto_20190904_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
