# Generated by Django 2.2.3 on 2019-09-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0005_auto_20190904_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='latest_login',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='login_count',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='modified_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
        ),
    ]
