# Generated by Django 2.2.3 on 2019-09-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0006_auto_20190907_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='thumbnail',
            field=models.BinaryField(null=True),
        ),
    ]
