# Generated by Django 2.2.3 on 2019-09-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0007_account_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orner', models.CharField(default='', max_length=255)),
                ('contributor_uid', models.CharField(db_index=True, default='', max_length=255)),
                ('contributor_account', models.CharField(db_index=True, default='', max_length=255)),
                ('body', models.TextField(db_index=True)),
                ('video_path', models.FilePathField(null=True)),
                ('video_thumbnail', models.BinaryField(db_index=True, null=True)),
                ('delete_flag', models.BooleanField(db_index=True, default=False)),
                ('created_datetime', models.DateTimeField(db_index=True)),
                ('modified_datetime', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_uid', models.CharField(db_index=True, default='', max_length=255)),
                ('commentator_account', models.CharField(db_index=True, default='', max_length=255)),
                ('body', models.TextField(db_index=True)),
                ('delete_flag', models.BooleanField(db_index=True, default=False)),
                ('created_datetime', models.DateTimeField(db_index=True)),
                ('modified_datetime', models.DateTimeField(db_index=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceApp.Article')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
