# Generated by Django 2.2.3 on 2019-10-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0009_auto_20190929_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
